### ISSUE TITLE
bug_stt_log

### ISSUE THREAD

**Issue by yyeennyy** [yyeennyy/VisualRadio#140]
# Issue
시스템 재부팅해도, 컨테이너를 재부팅해도 stt로그가 뜹니다.

# Detail
아래와 같이, stt와 관련 없는 과정에서 stt로그가 뜹니다. 
시스템 자체를 재부팅해도 마찬가지입니다.
수요일까지 해결 예정입니다. 기다려주세요. 

```
visual-radio  | WARNING:tensorflow:From /usr/local/lib/python3.8/site-packages/spleeter/separator.py:146: calling DatasetV2.from_generator (from tensorflow.python.data.ops.dataset_ops) with output_types is deprecated and will be removed in a future version.
visual-radio  | Instructions for updating:
visual-radio  | Use output_signature instead
visual-radio  | WARNING:tensorflow:From /usr/local/lib/python3.8/site-packages/spleeter/separator.py:146: calling DatasetV2.from_generator (from tensorflow.python.data.ops.dataset_ops) with output_shapes is deprecated and will be removed in a future version.
visual-radio  | Instructions for updating:
visual-radio  | Use output_signature instead
visual-radio  | 2023-09-11 20:26:19 |DEBUG| services.py:273 ...  services > [●●●●] sec_wav_list: [['sec_0', array([0.19611222, 0.2103714 , 0.20772618, ..., 0.06323321, 0.05940634,
visual-radio  |        0.05521922], dtype=float32)], ['sec_1', array([ 0.0512778 ,  0.04856004,  0.04442124, ..., -0.10672967,
visual-radio  |        -0.11385804, -0.11091355], dtype=float32)], ['sec_2', array([-0.08002008,  0.00464832, -0.11666928, ..., -0.00225557,
visual-radio  |        -0.01346225, -0.01918887], dtype=float32)], ['sec_3', array([-0.01852008, -0.01298604, -0.00539833, ...,  0.09085913,
visual-radio  |         0.06770968,  0.07900562], dtype=float32)], ['sec_4', array([ 0.07021023,  0.05995855,  0.05517017, ..., -0.1000219 ,
visual-radio  |         0.00940602,  0.13087524], dtype=float32)]]
**visual-radio  | 2023-09-11 20:26:20 |DEBUG|      stt.py:64  ...       STT > [stt] start!
visual-radio  | 2023-09-11 20:26:20 |DEBUG|      stt.py:67  ...       STT > [stt] 오디오 로드중..
visual-radio  | 2023-09-11 20:26:20 |DEBUG|      stt.py:89  ...       STT > [stt] DONE IN 0.382692813873291 SECONDS
visual-radio  | 2023-09-11 20:26:20 |DEBUG|      stt.py:150 ...       STT > [stt] script 생성 완료
visual-radio  | 2023-09-11 20:26:20 |DEBUG|    route.py:242 ...     route > empty vocabulary; perhaps the documents only contain stop words
visual-radio  | 2023-09-11 20:26:20 |DEBUG|    route.py:243 ...     route > 오류 발생!!!! 오디오 처리를 종료합니다.
visual-radio  | 2023-09-11 20:26:20 |DEBUG|    route.py:247 ...     route > Traceback (most recent call last):
visual-radio  |   File "/app/VisualRadio/route.py", line 222, in process_audio_file
visual-radio  |     paragraph.compose_paragraph(broadcast, name, date) # stt가 재진행되면 문단구성도 새로 해야 함
visual-radio  |   File "/app/./VisualRadio/paragraph.py", line 118, in compose_paragraph
visual-radio  |     vectorized = vectorizer.fit_transform(document)
visual-radio  |   File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 2126, in fit_transform
visual-radio  |     X = super().fit_transform(raw_documents)
visual-radio  |   File "/usr/local/lib/python3.8/site-packages/sklearn/base.py", line 1151, in wrapper
visual-radio  |     return fit_method(estimator, *args, **kwargs)
visual-radio  |   File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1383, in fit_transform
visual-radio  |     vocabulary, X = self._count_vocab(raw_documents, self.fixed_vocabulary_)
visual-radio  |   File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1289, in _count_vocab
visual-radio  |     raise ValueError(
visual-radio  | ValueError: empty vocabulary; perhaps the documents only contain stop words
visual-radio  |** 
visual-radio  | WARNING:tensorflow:From /usr/local/lib/python3.8/site-packages/keras/layers/normalization/batch_normalization.py:561: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
visual-radio  | Instructions for updating:
visual-radio  | Colocations handled automatically by placer.

```

**Comment by shxnzxxn** [comment]
그러니까, 지금 stt를 진행하는 상황이 아닌 mr 제거를 진행하는 상황인데, stt 로그가 뜬다는건가요??

어제 얘기해봤던, 버퍼 느낌일 수도 있겠네요... 디버깅에 시간 많이 쏟게되면 저한테 넘겨주세요.ㅇ
